input {
  file {
    path => "/var/log/app/application.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/application-log.sincedb"
    codec => json
  }
}

filter {
  mutate {
    add_field => { "[@metadata][target_index]" => "vs-lab1-logs" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}-%{+YYYY.MM.dd}"
  }
}

