--liquibase formatted sql

--changeset user-service:001-create-users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(320) NOT NULL,
    role VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_users_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'TEAM_LEAD', 'DEVELOPER'))
);
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));
