server:
  port: ${SERVER_PORT:8081}

spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - PreserveHostHeader
          routes:
            - id: users-api
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
            - id: tracker-api
              uri: lb://tracker-service
              predicates:
                - Path=/api/v1/projects/**,/api/v1/tasks/**,/api/v1/labels/**
            - id: users-openapi
              uri: lb://user-service
              predicates:
                - Path=/v3/api-docs/user-service
              filters:
                - SetPath=/v3/api-docs
            - id: tracker-openapi
              uri: lb://tracker-service
              predicates:
                - Path=/v3/api-docs/tracker-service
              filters:
                - SetPath=/v3/api-docs

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls:
      - name: user-service
        url: /v3/api-docs/user-service
      - name: tracker-service
        url: /v3/api-docs/tracker-service
